trigger:
- none

pool: testingpool

stages:
- stage: terraformInit
  displayName: terraform init
  pool: testingpool

  jobs:
  - job: terraforminit
    displayName: terraforminit
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'azure connection'
        backendAzureRmStorageAccountName: 'storage552'
        backendAzureRmContainerName: 'cont1'
        backendAzureRmKey: 'terraform.tfstate'

- stage: terraformplan
  displayName: terraform plan
  dependsOn: terraforminit
  pool: testingpool
  jobs:
    - job: terraformplan
      displayName: terraformplan
      
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'azure connection'
          backendAzureRmStorageAccountName: 'storage552'
          backendAzureRmContainerName: 'cont1'
          backendAzureRmKey: 'terraform.tfstate'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          environmentServiceNameAzureRM: 'azure connection'

- stage: terraformapply
  displayName: terraform apply
  dependsOn: terraformplan
  jobs:
  - job: waitForValidation
    displayName: Manual validation
    pool: server
    timeoutInMinutes: 90
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'ab@.com'
        instructions: 'please validate terraform plan'
  
  jobs:
    - job: terraformapply
      displayName: terraformapply
      
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'azure connection'
          backendAzureRmStorageAccountName: 'storage552'
          backendAzureRmContainerName: 'cont1'
          backendAzureRmKey: 'terraform.tfstate'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'apply'
          commandOptions: '--auto-approve'
          environmentServiceNameAzureRM: 'azure connection'
