trigger:
- none

pool: testingpool

stages:
- stage: terraformInit
  displayName: terraform init
  jobs:
  - job: terraforminit
    displayName: terraforminit
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'azure connection'
        backendAzureRmStorageAccountName: 'storage552'
        backendAzureRmContainerName: 'cont1'
        backendAzureRmKey: 'terraform.tfstate'

- stage: terraformplan
  displayName: terraform plan
  dependsOn: terraformInit
  jobs:
  - job: terraformplan
    displayName: terraformplan
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'azure connection'
        backendAzureRmStorageAccountName: 'storage552'
        backendAzureRmContainerName: 'cont1'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'azure connection'

- stage: terraformapply
  displayName: terraform apply
  dependsOn: terraformplan
  jobs:
  - job: waitForValidation
    displayName: Manual validation
    pool: server
    timeoutInMinutes: 90
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'ab@.com'     # ✅ yahan apna actual email daalna
        instructions: 'Please validate the Terraform plan before applying.'

  - job: terraformapply
    displayName: terraformapply
    dependsOn: waitForValidation   # ✅ pehle manual validation complete hona chahiye
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'azure connection'
        backendAzureRmStorageAccountName: 'storage552'
        backendAzureRmContainerName: 'cont1'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '--auto-approve'
        environmentServiceNameAzureRM: 'azure connection'
