
trigger:
- none

pool: testingpool

stages:
- stage: terraformInit
  displayName: terraform init
  pool: testingpool

  jobs:
  - job: terraforminit
    displayName: terraforminit
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'azure connection'
        backendAzureRmStorageAccountName: 'storage552'
        backendAzureRmContainerName: 'cont1'
        backendAzureRmKey: 'terraform.tfstate'

- stage: terraformplan
  displayName: terraform plan
  pool: testingpool
  jobs:
    - job: terraformplan
      displayName: terraformplan
      dependsOn: terraforminit
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'azure connection'
          backendAzureRmStorageAccountName: 'storage552'
          backendAzureRmContainerName: 'cont1'
          backendAzureRmKey: 'terraform.tfstate'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          environmentServiceNameAzureRM: 'azure connection'

- stage: terraformapply
  displayName: terraform apply
  pool: testingpool
  jobs:
    - job: terraformapply
      displayName: terraformapply
      dependsOn: terraformplan
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'azure connection'
          backendAzureRmStorageAccountName: 'storage552'
          backendAzureRmContainerName: 'cont1'
          backendAzureRmKey: 'terraform.tfstate'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'apply'
          commandOptions: '--auto-approve'
          environmentServiceNameAzureRM: 'azure connection'





